<template>
<landing-layout>
<banner-component :subtitle="subtitle"/>

<div class="container mt-4 mb-5 pb-5">
<div class="row">
<div class="col-12 col-md-8 offset-lg-2">
<div>
<h5>
Leveraging Uganda’s Natural Resources
</h5>
<p>
Uganda is endowed with rich ecosystems, including forests, wetlands, and biodiversity hotspots. These natural resources act as significant carbon sinks, absorbing large amounts of carbon dioxide. Projects such as afforestation, reforestation, and wetland restoration capitalise on these resources to generate carbon credits, which can be sold in markets.
</p>
</div>






<div class="mt-3">
<h5>
The Value of the Carbon Market
</h5>
<p>
The global carbon market is estimated to be worth over $850 billion annually, with Africa's share steadily growing. Uganda stands to gain significantly by tapping into this market. Estimates suggest Uganda could generate millions of dollars annually by monetizing its carbon sequestration efforts through verified carbon credits.
</p>
</div>


<div class="mt-3">
<h5>
Generating Carbon Credits
</h5>
<p>
Carbon credits are generated through activities that either reduce greenhouse gas emissions or remove carbon dioxide from the atmosphere.
</p>

<ol>
<li class="text-muted">
Afforestation/Reforestation: Planting trees to capture CO₂ from the atmosphere.
</li>
<li class="text-muted">
Wetland Restoration: Reviving degraded wetlands to enhance their carbon absorption capacity.
</li>
<li class="text-muted">
Renewable Energy Projects: Reducing emissions by replacing fossil fuels with solar, hydro, or wind energy.
</li>
<li class="text-muted">
Energy Efficiency Initiatives: Improving efficiency in industries and households to cut emissions.
</li>
</ol>
</div>




<div class="mt-3">
<h5>
Examples of Nature-Based Carbon Credit Projects
</h5>
<ol>
<li class="text-muted">
  Kakira Sugar Plantation: Carbon credits generated by using bagasse (sugarcane waste) as fuel for power generation instead of fossil fuels.
</li>
<li class="text-muted">
  Rwenzori Mountains Reforestation: Projects planting indigenous trees to restore forest cover and enhance biodiversity.
</li>
<li class="text-muted">
  Wetland Conservation in the Mabamba Bay: Protecting the wetlands that sequester carbon while supporting diverse bird species.
</li>
</ol>

</div>


<div class="mt-3">
<h5>
Supporting Climate Financing
</h5>
<p>
  Revenue from carbon credit sales funds climate mitigation and adaptation projects, enhances community livelihoods, and strengthens Uganda’s climate resilience. It also attracts international investment, aligning with Uganda’s Nationally Determined Contributions (NDCs) under the Paris Agreement.
</p>
</div>


</div>
</div>
</div>

</landing-layout>
</template>
<script>
import BannerComponent from '../components/BannerComponent.vue';
import LandingLayout from '../Layouts/LandingLayout.vue';
export default {
components: {
LandingLayout,
BannerComponent
},
data(){return{
subtitle:"Carbon credits are a vital tool for mobilising climate financing, leveraging Uganda’s abundant natural resources to address climate change while promoting sustainable development."


}},


computed:{
url(){
return this.$page.props.system.url;
}


}





}
</script>
<style scoped>
ul li, ol li{
margin-bottom: 10px;
list-style:lower-roman;
}
h1,h2,h3,h5,h5,h6{
letter-spacing: 0.3px;
}

</style>