<template>
<landing-layout>
<banner-component/>

<div class="container-fluid feature py-0">
<div class="container mt-5 mb-4">
<div class="text-center mx-auto wow fadeInUp" data-wow-delay="0.2s" style="max-width: 800px; visibility: visible; animation-delay: 0.2s; animation-name: fadeInUp;">
<subtitle-component :title="'Enhance your corporate social responsibility'"/>
<p>
As a local carbon registry dedicated to facilitating carbon credit generation and sustainable development, we invite businesses, organizations, and institutions to collaborate with us in our mission to mitigate climate change and promote environmental stewardship in Uganda.
</p>
</div>

</div>
</div>












<div class="container-fluid feature bg-white py-0">
<div class="container py-5">
<div class="row g-0 p-0">
<div class="col-md-6 bg-light d-flex align-items-center">
<div class="p-5">
<!-- <h6 class="section-title text-start text-uppercase mb-3">Luxury Living</h6> -->
<h4 class="mb-4">Why Partner with Us</h4>
<div class="mb-4">
<ul>
<li>
<p>
    Be part of Uganda's journey toward reducing greenhouse gas emissions through verified carbon credits and sustainable projects.
</p>
</li>
<li>
<p>
    Your partnership will contribute to projects that improve livelihoods, enhance climate resilience, and support Uganda’s environmental goals.
</p>
</li>

<li>
<p>
    Collaborate with us to offset your emissions through locally verified carbon credits generated by community-based and environmental projects.
</p>
</li>

<li>
<p>
    Demonstrate your organization's commitment to sustainability by supporting impactful carbon reduction projects that align with your CSR goals.
</p>
</li>
</ul>





</div>






<h4 class="mb-4 mt-4">Types of Partnerships</h4>
<div class="mb-4">
<p>

    We offer a variety of partnership models that align with the unique goals and values of our partners:
</p>
<ul class="mt-4">
<li>
<p>
<strong> Corporate Partnerships.</strong>
Businesses can collaborate with us to implement or sponsor carbon mitigation projects that align with their sustainability goals. Whether you want to reduce your carbon footprint, invest in local projects, or source carbon credits, Uganda Carbon Registry can help.

</p>
</li>
<li>
<p><strong> NGO and Development Partnerships.</strong>
    We collaborate with local and international NGOs to enhance the capacity of communities to implement carbon reduction projects and certify emissions reductions through our registry. You can work with us to design, implement, and monitor projects that generate both environmental and social benefits or partner with us to access funding for larger-scale carbon projects that require shared resources and expertise.
</p>
</li>

<li>
<p>
    <strong>Carbon Credit Buyers. </strong>
    If your organization seeks to offset its emissions, Uganda Carbon Registry provides a transparent and reliable source of verified carbon credits. By purchasing credits through us, you directly support community-led and environmentally beneficial projects in Uganda.
</p>
</li>

<li>
<p>
<strong>Academic and Research Collaborations.</strong>
Partnering with universities and research institutions allows us to deepen the knowledge base around carbon credit methodologies, climate finance, and the socio-economic impacts of carbon projects.

</p>
</li>
</ul>





</div>













</div>
</div>














<div class="col-md-6 bg-dark">
<div class="p-5">
<!-- <h6 class="section-title text-start text-white text-uppercase mb-3">Luxury Living</h6> -->
<h3 class="text-white mb-4 text-uppercase" style="line-height:40px;border-left:solid 5px white;padding-left:15px;">
    Make a difference on a global scale while supporting Uganda’s biodiversity and economy
</h3>

<p class="text-white mb-4">
    Our focus areas include renewable energy, reforestation and agroforestry, energy efficiency,
    Sustainable agriculture, wetland conservation, waste management, transport, community engagement, climate education, awareness, and policy development.

</p>


<h4 class="text-white mb-3 mt-5">
    Become a Partner Today
</h4>
<p class="text-white">
    Partner with Uganda Carbon Registry to drive impactful climate action and support the development of Uganda’s carbon credit market. Whether you are interested in sponsoring a project, purchasing carbon credits, or co-developing new initiatives, we are ready to collaborate with you.
</p>

<contact-info class="mt-5"/>
</div>
</div>
</div>
</div>
</div>










</landing-layout>
</template>
<script>
import LandingLayout from '../Layouts/LandingLayout.vue';
import BannerComponent from '../components/BannerComponent.vue';
import SubtitleComponent from '../components/SubtitleComponent.vue';
import ContactInfo from '../components/ContactInfo.vue';
export default {
components:{
LandingLayout,
BannerComponent,
SubtitleComponent,
ContactInfo

}
}
</script>
<style scoped>
ul li{
list-style-type:circle;
margin-bottom:15px;
}


p strong{
display: block;
font-weight:bold;
}

</style>