<template>
<landing-layout>
<banner-component/>

<div class="container-fluid feature bg-white py-0">
<div class="container py-5">
<div class="text-center mx-auto wow fadeInUp" style="max-width: 800px;">

<p class="mb-0 text-left">
Offset your carbon footprint and contribute to climate action by purchasing carbon credits through the Uganda Carbon Registry. Support local projects that reduce greenhouse gas emissions while promoting sustainable development in Uganda’s communities.
</p>

</div>
</div>
</div>












<div class="container-fluid feature bg-white py-0">
<div class="container py-3">
<div class="row g-0 p-0">
<div class="col-md-6 bg-light d-flex align-items-center">
<div class="p-5">



<h4 class="mb-2">What Are Carbon Credits?</h4>
<p class="mb-4">
A carbon credit represents the reduction or removal of one ton of carbon dioxide (CO2) or its equivalent in other greenhouse gases.
By purchasing carbon credits, you can offset the emissions generated by your activities whether it’s from travel, business operations, or everyday living while funding projects that create measurable environmental benefits.
</p>





<h4 class="mb-2 mt-5">Why Buy Carbon Credits Us?</h4>
<p class="mb-4">
When you buy carbon credits from the Uganda Carbon Registry, you are directly supporting verified carbon reduction projects that deliver both environmental and social impact. Here’s why purchasing through us makes a difference:
</p>
<ul>
<li>
<p>
Create local impact. Your purchase supports projects in Uganda, helping to protect local ecosystems, reduce emissions, and foster sustainable livelihoods.
</p>
</li>
<li>
<p>
Verified projects. All carbon credits sold through our registry are from independently verified projects that meet global standards, ensuring transparency and accountability.
</p>
</li>
<li>
<p>
Support sustainable development. Our projects focus on more than just reducing emissions. They also contribute to job creation, community development, and biodiversity conservation in Uganda’s most vulnerable areas.
</p>
</li>
<li>
<p>
Carbon neutrality. Achieve your sustainability goals by offsetting unavoidable emissions and demonstrating your commitment to environmental responsibility.
</p>
</li>
</ul>




<h4 class="mb-2 mt-5">Our Carbon Credit Projects</h4>
<p class="mb-4">
We offer a diverse portfolio of high-impact projects designed to reduce greenhouse gas emissions and promote sustainable development in Uganda. When you buy carbon credits, you are helping to support  reforestation and afforestation, renewable energy, sustainable agriculture, energy efficiency, waste management and methane capture among others.
</p>



<h4 class="mb-2 mt-5">Why Offsetting Matters?</h4>
<p class="mb-4">
    Offsetting your emissions helps to balance your carbon footprint by supporting projects that remove or prevent the equivalent amount of CO2 from being released into the atmosphere. By purchasing carbon credits, you neutralize emissions, help Uganda and the world move closer to meeting international climate targets such as the Paris Agreement and support the protection of Uganda’s ecosystems and natural resources.
</p>


<div style="height:200px;"></div>








</div>
</div>
<div class="col-md-6 bg-dark col-12">
<div class="p-5">


<h2 class="text-white mb-4 title-border-left pl-2 text-uppercase">Show Your Commitment Now</h2>
<p class="text-white mb-4">Demonstrate your dedication to sustainability and climate action by investing in carbon credits.</p>



<h4 class="mb-2 mt-5 text-white">How to Buy Carbon Credits?</h4>
<p class="mb-4 text-white">
Purchasing carbon credits through the Uganda Carbon Registry is simple and transparent:
</p>


<ul>
<li>
<p class="text-white">
Calculate your carbon footprint. The first step is to understand your emissions. Use our carbon calculator or contact us for assistance in measuring your carbon footprint—whether for personal, corporate, or event-related emissions.
</p>
</li>

<li>
<p class="text-white">
Select a project. Explore our verified projects and choose one that aligns with your sustainability goals. Each project is accompanied by detailed information on its environmental and social impact.
</p>
</li>

<li>
<p class="text-white">
Purchase carbon credits. After selecting a project, you can easily purchase the number of carbon credits needed to offset your emissions. All purchases are made through our secure online platform.
</p>
</li>

<li>
<p class="text-white">
Receive your certification. Once your purchase is complete, you will receive an official certificate that verifies your carbon credits and outlines the emissions reduction achieved.
</p>
</li>
<li>
<p class="text-white">
Track the impact. Stay informed about the ongoing progress of the projects you support. We provide regular updates and reports on how your contribution is making a difference.
</p>
</li>


</ul>



<h4 class="mb-2 mt-5 text-white">Who Can Buy Carbon Credits?</h4>
<p class="text-white mb-4 ">
    Whether you are an individual, business, or organization, buying carbon credits is an effective way to contribute to climate action and sustainability:
</p>


<ul>
    <li>
    <p class="text-white">
    Individuals. Offset your personal carbon footprint from activities such as travel, commuting, or home energy use.
    </p>
    </li>

    <li>
    <p class="text-white">
    Businesses. Achieve your corporate sustainability goals by offsetting operational emissions and enhancing your corporate social responsibility (CSR) efforts.
    </p>
    </li>

    <li>
    <p class="text-white">
    Events. Make your events carbon-neutral by offsetting emissions from travel, logistics, and energy use. </p>
    </li>

    <li>
    <p class="text-white">
    Nonprofits and Government agencies. Offset emissions from day-to-day operations while supporting Uganda’s climate resilience efforts.
    </p>
    </li>
    </ul>


    <h4 class="mb-2 mt-5 text-white">Start Offsetting Today</h4>
<p class="text-white mb-4 ">
    Make a difference today by offsetting your emissions through Uganda Carbon Registry. Your purchase of carbon credits funds projects that deliver long lasting environmental and social impact across Uganda.
</p>

<div>
<Inertia-link :href="route('login')" class="btn btn-danger btn-lg p-3" style="border-radius:0;border:none;">Buy Now </Inertia-link>
</div>


</div>
</div>
</div>
</div>
</div>






</landing-layout>
</template>
<script>
import LandingLayout from '../Layouts/LandingLayout.vue';
import BannerComponent from '../components/BannerComponent.vue';
export default {
components:{
LandingLayout,
BannerComponent,
},

data(){return{






}}
}
</script>
<style scoped>
ol li{
margin-bottom:10px;
padding:5px;
list-style:disc;
}

ul li{
margin-bottom:10px;
padding:5px;
list-style:lower-roman;
}

.project ol li p{
color:white;
}
</style>